version: '2'

services:
  proxy:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - api
      - dashboard
      - landing
  api:
    build: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - db
  dashboard:
    build: ./dashboard
    volumes:
      - /app/node_modules
      - ./dashboard:/app
    depends_on:
      - db
  landing:
    build: ./landing
    volumes:
      - /app/node_modules
      - ./landing:/app
  server-builder:
    build: ./server-builder
    volumes:
      - /app/node_modules
      - ./server-builder:/app
    depends_on:
      - redis
  redis:
    image: 'redis:latest'
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'